

K-means clustering:

```{r}
# Load the required libraries for K-means clustering
library(cluster)

# Select the columns of interest (e.g., mechanism of action)
drug_data <- new_prism.treat$moa

# Determine the number of unique data points
num_unique <- length(unique(drug_data))
num_unique

# Perform K-means analysis
# Let's assume we want to create x clusters
kmeans_result <- kmeans(drug_data, centers = num_unique)

# Visualize the clustering results
plot(drug_data, col = kmeans_result$cluster, pch = 16)

```



Target analysis:
```{r}
# Load the required libraries
library(dplyr)
library(ggplot2)

# Load the drug data (using the prism.treat table)
drug_data <- new_prism.treat

# Count the frequency of each target
target_counts <- drug_data %>% count(target)

# Sort the target counts in descending order
target_counts <- target_counts[order(-target_counts$n), ]

# Plot the target distribution
ggplot(target_counts, aes(x = reorder(target, -n), y = n)) +
  geom_bar(stat = "identity", fill = "blue") +
  xlab("Target") +
  ylab("Frequency") +
  ggtitle("Distribution of Drug Targets")
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

count(target)
target_counts
drug_data_target <- as.factor(drug_data$target)
drug_data_target
summary(drug_data_target)
```


Determining Therapeutic Strategies: 
The most frequently occurring targets can be used to determine therapeutic strategies, such as in cancer treatment. These targets can target therapeutic agents and drugs that may be effective in specific types of cancer.
```{r}
#How frequent do the targets occur?
## top 5 targets:
 
target_summary <- summary(drug_data_target)
top_targets <- head(target_summary, 5)
#top_targets

drug_data_target

# Filter the top 20 most frequently occurring targets
top_20_targets <- head(summary(drug_data_target), 20)
top_20_targets

# Plot the histogram
barplot(top_20_targets, main = "Top 20 Most Frequent Targets",
        xlab = "Target", ylab = "Frequency", las = 2,
        col = "skyblue", border = "white", horiz = FALSE)


```

```{r}
selected_drugs_liver <- unique(selected_drugs_liver_all)

# Filtreleme işlemi
selected_drugs_liver_prism.treat <- prism.treat[prism.treat$broad_id %in% selected_drugs_liver, ]

selected_drugs_liver_prism.treat


#target
liver_target <- as.factor(selected_drugs_liver_prism.treat$target)

top_20_targets_liver <- head(summary(liver_target), 20)
top_20_targets_liver


barplot(top_20_targets_liver, main = "Top 20 Most Frequent Targets",
        xlab = "Target", ylab = "Frequency", las = 2,
        col = "skyblue", border = "white", horiz = FALSE, cex.names = 0.5)


#mechanism of action
liver_moa <- as.factor(selected_drugs_liver_prism.treat$moa)

top_10_targets_moa <- head(summary(liver_moa), 10)
top_10_targets_moa

barplot(top_10_targets_moa, main = "Top 10 Most Frequent Mechanism of Action",
        xlab = "Mechanism of Action", ylab = "Frequency", las = 2,
        col = "skyblue", border = "white", horiz = FALSE, cex.names = 0.3)

```




Mechanism of actions:
```{r}
drug_data_moa <- as.factor(drug_data$moa)
moa_summary <- summary(drug_data_moa)
top_moas <- head(moa_summary, 5)
top_moas
```




```{r}
# Load the required libraries
library(dplyr)
library(ggplot2)

# Load the drug data (using the prism.treat table)
drug_data <- new_prism.treat

# Define the mechanism variable as a factor
drug_data$mechanism <- as.factor(drug_data$moa)

# Count the frequency of each mechanism
mechanism_counts <- drug_data %>% count(moa)

# Sort the mechanism counts in descending order
mechanism_counts <- mechanism_counts[order(-mechanism_counts$n), ]

# Plot the mechanism distribution
ggplot(mechanism_counts, aes(x = reorder(moa, -n), y = n)) +
  geom_bar(stat = "identity", fill = "blue") +
  xlab("Mechanism") +
  ylab("Frequency") +
  ggtitle("Distribution of Drug Mechanisms") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```



```{r}
# Hedef bölgelerin analizine odaklanmak için prism.treat tablosunu kullanın
# İlaçların mechanism of action ve target bilgilerini içeren sütunları seçin
target_data <- new_prism.treat[, c("moa", "target")]
target_data

# Her bir sütunun eksik değerlerini en çok tekrar eden değerle doldurma
for (col in colnames(target_data)) {
  col_values <- target_data[, col]
  most_frequent_value <- names(which.max(table(col_values)))
  col_values[is.na(col_values)] <- most_frequent_value
  target_data[, col] <- col_values
}

# Mekanizma ve hedef bölgeleri faktör olarak tanımlayın
target_data_moa <- as.factor(target_data$moa)
target_data_target <- as.factor(target_data$target)

# Mekanizma ve hedef bölgelerine göre etkili konsantrasyonları analiz edin
result <- tapply(rownames(target_data), list(target_data_moa, target_data_target), mean)

# Elde edilen analiz sonuçlarını görselleştirin
heatmap(result, Rowv = NA, Colv = NA, col = cm.colors(256))


```





