
```{r}
# how is the correlation for different concentrations of drugs to the growth rate of the cell lines?

concentrations_nM <- c(0.6, 2.4, 9.8, 39.1, 156.3, 625, 10000, 2500)

cell_growth_rate_BRD_A00077618_236_07_6 <- prism[1, 1:8]

cell_growth_rate_BRD_A00758722_001_04_9 <- prism[1, 9:16]

BRD_A00077618_236_07_6 = c(t(cell_growth_rate_BRD_A00077618_236_07_6))
BRD_A00758722_001_04_9 = c(t(cell_growth_rate_BRD_A00758722_001_04_9))



plot(concentrations_nM, cell_growth_rate_BRD_A00758722_001_04_9, main="ACH_007", xlab="concentrations of drugs in nM", ylab="cell growth rate", pch=20, cex=1.5, col="green" )
points(concentration_nM, cell_growth_rate_BRD_A00077618_236_07_6, pch=20, cex=1.5, col="red")

cor(BRD_A00077618_236_07_6, BRD_A00758722_001_04_9, method = "pearson")

```

```{r}
# A vector that includes information about all the drugs and the 8 specific doses:
all_drug_names <- colnames(prism)
concentrations <- c(0.00061034, 0.0024414, 0.00976562, 0.0390625, 0.15625, 0.625, 10, 2.5)

# Split the drug names into groups with each 8 elements to make groups of every single drug.
all_drugs_grouped <- split(all_drug_names, rep(1:(length(all_drug_names)/8), each = 8))
all_drugs_grouped


# We select a random group to see if the function works:
selected_group_1 <- all_drugs_grouped[[1]]
selected_group_1


# plotting exercise using the selection method:

concentrations_nM <- c(0.6, 2.4, 9.8, 39.1, 156.3, 625, 10000, 2500)
y1 <- c(t(prism[1, selected_group_1]))
y1

regression_model_1 <- lm(y1 ~ concentrations_nM)
regression_model_1
plot(concentrations_nM, y1, pch=16, cex=1.3, col="blue")
abline(lm(y1 ~ concentrations_nM))

plot(concentrations_nM, y1, main="ACH_007", xlab="concentrations of drugs in nM", ylab="cell growth rate", pch=20, cex=1.5, col="green" )  # it works :)



```



```{r}
all_drugs_grouped_ <- list(all_drugs_grouped)

regression_results <- list()

for (i in 1:length(all_drugs_grouped_)) {
  drug_group <- all_drugs_grouped_[[i]]
  cell_growth_rates <- c(t(prism_for_liver[, all_drug_names]))
  model <- lm(cell_growth_rates ~ concentrations_nM, data=drug_group)
  regression_results[[i]] <- summary(model)
}
```


```{r}
# For döngüsü
for (i in 1:length(all_drugs_grouped)) {
  # İlaç grubuna ait verileri alın
  ilaç_grubu <- all_drugs_grouped[[i]]
  
  # İlaç grubu adını yazdırın
  cat("İlaç Grubu:", names(all_drugs_grouped)[i], "\n")
  
  # Linear regresyon analizini yapın
  for (j in 1:8) {
    # İlgili ilacın hücre büyüme değerlerine erişin
    cell_growth_rates <- ilaç_grubu[, j]
    
    # İlaç konsantrasyonları
    concentrations_nM <- c(0.00061034, 0.0024414, 0.00976562, 0.0390625, 0.15625, 0.625, 10, 2.5)
    
    # Linear regresyon analizi
    regression_model <- lm(cell_growth_rates ~ concentrations_nM)
    
    # Regresyon sonuçlarını yazdırın
    cat("İlaç:", colnames(ilaç_grubu)[j], "\n")
    print(summary(regression_model))
    cat("\n")
  }
}

```

```{r}
treatment_ids = unique(prism.treat$broad_id)
treatment_ids

test = t(prism[, grep("BRD-A00758722-001-04-9", colnames(prism))])
test


for (x in treatment_ids)
  print(t(prism_for_liver[, grep(x, colnames(prism_for_liver))]))


concentrations_in_nM = sub(".*::(.*?)::.*", "\\1", rownames(test))
concentrations_in_nM

sub(".*::(.*?)::.*", "\\1", colnames(prism))

cell_growth_rates_ <- t(prism[, grep(x, colnames(prism))])
cell_growth_rates_

# Her bir ilaç için linear regresyon analizi yapın
for (x in treatment_ids) {
  
  cell_growth_rates_each_treatment <- for (x in treatment_ids)
    print(t(prism_for_liver[, grep(x, colnames(prism_for_liver))]))
  
  # Linear regresyon analizi
  regression_model <- lm(cell_growth_rates_each_treatment ~ concentrations_in_nM)
  
  # İlaç adını yazdırın
  cat("İlaç:", x, "\n")
  
  # Regresyon sonuçlarını yazdırın
  print(summary(regression_model))
  
  cat("\n")
}



# Her bir ilaç için linear regresyon analizi yapın
for (x in treatment_ids) {
  
  cell_growth_rates_each_treatment <- t(prism_for_liver[, grep(x, colnames(prism_for_liver))])
  concentrations_in_nM <- sub(".*::(.*?)::.*", "\\1", rownames(cell_growth_rates_each_treatment))
  
  # Linear regresyon analizi
  regression_model <- lm(cell_growth_rates_each_treatment ~ as.numeric(concentrations_in_nM))
  
  # İlaç adını yazdırın
  cat("İlaç:", x, "\n")
  
  # Regresyon sonuçlarını yazdırın
  print(summary(regression_model))
  
  cat("\n")
}


#For the cell line ACH-000217:

prism_ACH_000221 <- prism_for_liver[2,]
t(prism_ACH_000221)

# Her bir ilaç için linear regresyon analizi yapın
for (x in treatment_ids) {
  
  cell_growth_rates_each_treatment <- t(prism_ACH_000221[, grep(x, colnames(prism_for_liver))])
  concentrations_in_nM <- sub(".*::(.*?)::.*", "\\1", rownames(cell_growth_rates_each_treatment))
  
  # Linear regresyon analizi
  regression_model <- lm(cell_growth_rates_each_treatment ~ as.numeric(concentrations_in_nM))
  
  # İlaç adını yazdırın
  cat("İlaç:", x, "\n")
  
  # Regresyon sonuçlarını yazdırın
  print(summary(regression_model))
  
  cat("\n")
}


plot(concentrations_in_nM, cell_growth_rates_each_treatment, pch=16, cex=1.3, col="blue")
abline(lm(y1 ~ concentrations_nM))

```


# which drugs inhibit the cell growth rate in liver cancer cell lines?

```{r}
# the indices of the liver cancer cell lines on the prism table:
liver_cancer_cell_lines
liver_cancer_cl_indices


for (x in liver_cancer_cl_indices)
    print(prism[x,])

# we created a new table by combining the rates of cell growth only for liver cancer cell lines:

liver_cancer_cl_indices = which(new_prism.cl$lineage == "liver")
length(liver_cancer_cl_indices)
liver_cancer_cl_indices

prism_for_liver_withNAs = rbind(prism[liver_cancer_cl_indices,])
prism_for_liver_withNAs

sum(is.na(prism_for_liver_withNAs)) #15191 NAs
sum(apply(prism_for_liver_withNAs, 2, function(x){any(is.na(x))})) #6560 Spalten mit NA`s


# we should remove all NAs from the prism table for liver cancer cell lines and substitute the NAs with the mean value of columns.

prism_for_liver <- as.data.frame(apply(prism_for_liver_withNAs, 2, function(x) {
    is_na <- is.na(x)
    x[is_na] <- mean(x, na.rm = TRUE)
    return(x)
}))

prism_for_liver

sum(is.na(prism_for_liver)) # => there are 0 NAs :)

columns_withNAs = colnames(prism_for_liver_withNAs)[colSums(is.na(prism_for_liver_withNAs)) > 0]


# we can try to make a heatmap

library(pheatmap)
heatmap_liver <- pheatmap(prism_for_liver, show_rownames = TRUE, show_colnames = FALSE)
heatmap_liver

## Histogram: "Effect of the drugs on the cell growth"
vector_liver <- unlist(sapply(prism_for_liver, function(x) x[is.numeric(x)]))
vector_liver <- na.omit(vector_liver)
hist(vector_liver, breaks = 100, xlab = "cell growth", main = "Effect of the drugs on the cell growth", xlim = c(-6, 2)); abline(v = mean(vector_liver, na.rm = TRUE), col = "blue", lwd = 2, lty = 3); abline(v = median(vector_liver, na.rm = TRUE), col = "green", lwd = 2, lty= 3); legend("topright", legend = c("mean", "median"), col = c("blue", "green"), lwd = 2, lty = 3)
```



```{r}

# what is the correlation between the drugs?

cor_liver_drugs <- cor(prism_for_liver, method = "pearson")



# we should set a threshold for the growth rate to find out the most effective drugs to stop cell growth.

for (x in liver_cancer_cl_indices)
    print(colnames(prism[which(prism[x,]< -2)]))


# saving for-loop in a vector

inhibiting_drugs_liver_cancer <- character()
inhibiting_drugs_liver_cancer

for (x in liver_cancer_cl_indices) {
    my_out <- colnames(prism[which(prism[x,]< -2)])
    inhibiting_drugs_liver_cancer <- c(my_out)
}
    
inhibiting_drugs_liver_cancer

library(dplyr)

# z.B. the 10000 nM concentrated drug BRD-A00758722-001-04-9 inhibits the cell growth and we find out its mechanism from the table new_prism.treat:

new_prism.treat %>% filter_all(any_vars(. %in% c('BRD-A00758722-001-04-9')))

new_prism.treat %>% filter_all(any_vars(. %in% inhibiting_drugs_liver_cancer))


which(new_prism.treat[inhibiting_drugs_liver_cancer,])



```


```{r}
# PCA:

pca_prism_for_liver = prcomp(prism_for_liver)
pca_prism_for_liver

# let's find out the pca values for each liver cancer cell line:
pca_values_for_liver = pca_prism_for_liver$x
pca_values_for_liver

# what are the variances of these principle components?
pca_variances_for_liver = pca_prism_for_liver$sdev^2
pca_variances_for_liver

# which principle components are more important?
pca_relation = pca_variances_for_liver/sum(pca_variances_for_liver)
pca_relation

# how important are these principal components?
plot(1:length(pca_variances_for_liver), pca_variances_for_liver, type = "b", ylab = "Variance", xlab = "Principal Component")


# let's plot the most important 2 principal components:
plot(pca_values_for_liver[,1],pca_values_for_liver[,2], xlab = "PC1", ylab = "PC2")

```

