---
title: "Report"
output: html_document
date: "2023-07-12"
---

Report

Methods:
Developing a Linear Regression Model

By examining the impact of drugs on cell growth at various concentrations, we have gained valuable insights into their potential as cancer treatments. Through linear regression analysis we have been able to determine the relationship between concentrations of several drugs and their effects on cell growth. We used the built-in function lm to do the training. This allows us to estimate how different concentrations may effect cell growth and identify the optimal concentration for inhibiting cancer cell growth. By combining this knowledge with information on the mechanisms of action and target sites of these drugs, we can explore potential solutions for cancer treatment. This approach enables us to identify promising drug candidates and optimize their dosage strategies, with the aim of maximizing their efficacy while minimizing adverse effects, offering new possiblities in the field of cancer therapy.



Results:

Determining Therapeutic Strategies: 
By analyzing the information in the "prism.treat", we can identify the targets of each drug and determine which targets are more frequently observed. This knowledge provides us with valuable insights for drug repurposing in cancer therapy.
```{r}
drug_data_target <- as.factor(prism.treat$target)

top_20_targets <- head(summary(drug_data_target), 20)
top_20_targets


barplot(top_20_targets, main = "Top 20 Most Frequent Targets",
        xlab = "Target", ylab = "Frequency", las = 2,
        col = "skyblue", border = "white", horiz = FALSE)


```
Understanding which targets are more commonly targeted by drugs allows us to identify potential opportunities for repurposing existing drugs for cancer treatment. If a specific target is highly frequent among different drugs, it suggests that this target might play cruical role in cancer biology. By leveraging the knowledge of highly targeted proteins or molecules, we can focus our efforts on designing novel treatment strategies that specifically aim to modulate these targets. It helps us to identify key pathways and biological processes that are commonly dysregulated in cancer cells. This knowledge can guide the development of targeted therapies that disrupt specific pathways or processes critical for cancer cell survival and growth.

MTOR (mechanistic target of rapamycin) and EGFR (epidermal growth factor receptor) are two of the most frequently targeted proteins in cancer therapy due to their critical roles in promoting cancer cell growth and survival. 

The MTOR pathway is a key regulator of cell growth, proliferation and metabolism, and its dysregulation has been implicated in various cancer types. Activation of the MTOR pathway stimulates protein synthesis and cell cycle progression, promoting uncontrolled cell growth and tumor development. Targeting MTOR signaling has shown promising results in inhibiting cancer cell proliferation and inducing cell death.

EGFR, a receptor tyrosine kinase, is frequently overexpressed or mutated in various cancers. Its aberrant activation leads to increased cell proliferation, survival and metastasis, contributing to tumor progressiond and resistance to therapy. Targeting EGFR with specific inhibitors has demonstrated significant clinical benefits in several cancer types, particularly in non-smell cell lung cancer and colorectal cancer. Inhibition of EGFR signaling pathways impedes cancer cell growth and survival and combination therapies involving EGFR have shown enhanced efficacy in certain patient populations.



Developing a Linear Regression Model

To move on with the linear regression, we determined an optimal threshold for the R^2 value which served as a criterion for assessing the reliability of linear regression analyses. Drugs that exhibited an R^2 value above this threshold were considered reliable in terms of their efficacy. For each distinct liver cancer cell line, we filtered the drugs that met the reliablity criterion, resulting in a subset of drugs with reliable regression models. We then examined the frequency of occurence for these reliable drugs across the different liver cancer cell lines. By identifying the most frquently occuring drug, we obtained the linear regression results with the highest consistency and reliability. In our case, for the liver cancer cell lines, our analyses resulted that the drug "BRD_K70358946_001_15_7" occur 8 times in 17 cancer cell lines which is almost the half of them.



Discussion:
Plotting the linear regression results for this drug allowed us to visualize its impact on cell growth in liver cancer. This integrated approach, combining regression analysis, filtering based on reliability, and examining drug frequencies, provides insights into the drugs that exhibit strong regression relationships and their potential for effective treatment in liver cancer. By predicting the most efficient concentrations for a stronger inhibition, we can have different therapy possibilities for cancer.






